import type { Metadata } from "next";
import "./globals.css";
import { PlaylistsProvider } from "@/hooks/usePlaylists";

export const metadata: Metadata = {
  title: "Blu3",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`marmelat  text-black h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <PlaylistsProvider>
          {children}
        </PlaylistsProvider>
      </body>
    </html>
  );
}
